### ISSUE TITLE
Feature: Length of Title 7-13 words

### ISSUE THREAD

**Issue by melodykaagman** [happyfuntimegroup/machinelearning#19]
# Length of Title 7-13 words
Titles play an essential role in capturing the overall meaning of a paper. Previously published work investigating this question agrees that the title length can impact citation rates.

## Pseudocode:
- 

## Reference:
https://www.natureindex.com/news-blog/five-features-highly-cited-scientific-article

**Comment by AdeV-Oly** [comment]
Entire dataset:
- Scatterplot:
![image](https://user-images.githubusercontent.com/78648959/144726061-0dafc6b1-4c88-4218-8ccf-8d0b229ded94.png)
- Pearson r: (-0.0628756568735512, 5.097976127340466e-08)
